# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlagents/envs/communicator_objects/custom_reset_parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlagents/envs/communicator_objects/custom_reset_parameters.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=_b('\252\002\034MLAgents.CommunicatorObjects'),
  serialized_pb=_b('\n@mlagents/envs/communicator_objects/custom_reset_parameters.proto\x12\x14\x63ommunicator_objects\"\xbb\x01\n\x15\x43ustomResetParameters\x12\x0c\n\x04seed\x18\x01 \x01(\x05\x12O\n\nproperties\x18\x02 \x03(\x0b\x32;.communicator_objects.CustomResetParameters.PropertiesEntry\x12\x10\n\x08\x65ncoding\x18\x03 \x03(\x02\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1f\xaa\x02\x1cMLAgents.CommunicatorObjectsb\x06proto3')
)




_CUSTOMRESETPARAMETERS_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='communicator_objects.CustomResetParameters.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communicator_objects.CustomResetParameters.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communicator_objects.CustomResetParameters.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=278,
)

_CUSTOMRESETPARAMETERS = _descriptor.Descriptor(
  name='CustomResetParameters',
  full_name='communicator_objects.CustomResetParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='communicator_objects.CustomResetParameters.seed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='communicator_objects.CustomResetParameters.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='communicator_objects.CustomResetParameters.encoding', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMRESETPARAMETERS_PROPERTIESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=278,
)

_CUSTOMRESETPARAMETERS_PROPERTIESENTRY.containing_type = _CUSTOMRESETPARAMETERS
_CUSTOMRESETPARAMETERS.fields_by_name['properties'].message_type = _CUSTOMRESETPARAMETERS_PROPERTIESENTRY
DESCRIPTOR.message_types_by_name['CustomResetParameters'] = _CUSTOMRESETPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomResetParameters = _reflection.GeneratedProtocolMessageType('CustomResetParameters', (_message.Message,), dict(

  PropertiesEntry = _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), dict(
    DESCRIPTOR = _CUSTOMRESETPARAMETERS_PROPERTIESENTRY,
    __module__ = 'mlagents.envs.communicator_objects.custom_reset_parameters_pb2'
    # @@protoc_insertion_point(class_scope:communicator_objects.CustomResetParameters.PropertiesEntry)
    ))
  ,
  DESCRIPTOR = _CUSTOMRESETPARAMETERS,
  __module__ = 'mlagents.envs.communicator_objects.custom_reset_parameters_pb2'
  # @@protoc_insertion_point(class_scope:communicator_objects.CustomResetParameters)
  ))
_sym_db.RegisterMessage(CustomResetParameters)
_sym_db.RegisterMessage(CustomResetParameters.PropertiesEntry)


DESCRIPTOR._options = None
_CUSTOMRESETPARAMETERS_PROPERTIESENTRY._options = None
# @@protoc_insertion_point(module_scope)
